---
title: "MC plots"
author: "mike"
date: "August 9, 2016"
output: html_document
---

```{r pkgs, message=FALSE,warning=FALSE,echo=FALSE}

library(ordinal)
library(splines)
library(gridExtra)
library(ggplot2)
library(reshape)
theme_set(theme_bw())

```

# Condom Status 

```{r condom status, echo=FALSE,message=FALSE,warning=FALSE}
load(".condomStatus_varlvlsum.RData")
source("ordfuns.R")
source("plotFuns.R")
catNames <- c("religion","urRural","job","maritalStat","MCCategory")
predNames <- predfun("status")
source("iso.R",echo=FALSE, verbose=FALSE)

grid.arrange(varPlot(rename(isoList[[1]],c(age="Age")),P=varlvlsum$`Pr(>Chisq)`[1]),
             varPlot(rename(isoList[[2]],c(wealth="Wealth")),P=varlvlsum$`Pr(>Chisq)`[2]),
             varPlot(rename(isoList[[3]],c(religion="Religion")),P=varlvlsum$`Pr(>Chisq)`[3]),
             varPlot(rename(isoList[[4]],c(edu="Education")),P=varlvlsum$`Pr(>Chisq)`[4]),
             varPlot(rename(isoList[[5]],c(urRural="Area")),P=varlvlsum$`Pr(>Chisq)`[5]),
             varPlot(rename(isoList[[6]],c(job="Job")),P=varlvlsum$`Pr(>Chisq)`[6]),
             varPlot(rename(isoList[[7]],c(maritalStat="Marital Status")),P=varlvlsum$`Pr(>Chisq)`[7]),
             varPlot(rename(isoList[[8]],c(media="Media")),P=varlvlsum$`Pr(>Chisq)`[8]),
             varPlot(rename(isoList[[9]],c(knowledge="Knowledge")),P=varlvlsum$`Pr(>Chisq)`[9]),
             nrow=3)

source("intfuns.R")
source("intplot.R")

print(varlvlsum)
source("effectSize.R")

```

# Partner Status Year

```{r partner status year, echo=FALSE,message=FALSE,warning=FALSE}
load(".partnerYearStatus_varlvlsum.RData")
source("ordfuns.R")
source("plotFuns.R")
catNames <- c("religion","urRural","job","maritalStat","MCCategory")
predNames <- predfun("status")
source("iso.R",echo=FALSE, verbose=FALSE)

grid.arrange(varPlot(rename(isoList[[1]],c(age="Age")),P=varlvlsum$`Pr(>Chisq)`[1]),
             varPlot(rename(isoList[[2]],c(wealth="Wealth")),P=varlvlsum$`Pr(>Chisq)`[2]),
             varPlot(rename(isoList[[3]],c(religion="Religion")),P=varlvlsum$`Pr(>Chisq)`[3]),
             varPlot(rename(isoList[[4]],c(edu="Education")),P=varlvlsum$`Pr(>Chisq)`[4]),
             varPlot(rename(isoList[[5]],c(urRural="Area")),P=varlvlsum$`Pr(>Chisq)`[5]),
             varPlot(rename(isoList[[6]],c(job="Job")),P=varlvlsum$`Pr(>Chisq)`[6]),
             varPlot(rename(isoList[[7]],c(maritalStat="Marital Status")),P=varlvlsum$`Pr(>Chisq)`[7]),
             varPlot(rename(isoList[[8]],c(media="Media")),P=varlvlsum$`Pr(>Chisq)`[8]),
             varPlot(rename(isoList[[9]],c(knowledge="Knowledge")),P=varlvlsum$`Pr(>Chisq)`[9]),
             nrow=3)

source("intfuns.R")
source("intplot.R")

print(varlvlsum)

source("effectSize.R")

```

# Condom Recency

```{r condom recency, echo=FALSE,message=FALSE,warning=FALSE}
load(".condomRecency_varlvlsum.RData")
source("ordfuns.R")
source("plotFuns.R")
catNames <- c("religion","urRural","job","maritalStat","MCCategory")
predNames <- predfun("recency")
source("iso.R",echo=FALSE,verbose = FALSE)
isoList[[10]]$MCCategory <- factor(isoList[[10]]$MCCategory,levels=c("No","Old","New"))
grid.arrange(varPlot(rename(isoList[[1]],c(age="Age")),P=varlvlsum$`Pr(>Chisq)`[1]),
             varPlot(rename(isoList[[2]],c(wealth="Wealth")),P=varlvlsum$`Pr(>Chisq)`[2]),
             varPlot(rename(isoList[[3]],c(religion="Religion")),P=varlvlsum$`Pr(>Chisq)`[3]),
             varPlot(rename(isoList[[4]],c(edu="Education")),P=varlvlsum$`Pr(>Chisq)`[4]),
             varPlot(rename(isoList[[5]],c(urRural="Area")),P=varlvlsum$`Pr(>Chisq)`[5]),
             varPlot(rename(isoList[[6]],c(job="Job")),P=varlvlsum$`Pr(>Chisq)`[6]),
             varPlot(rename(isoList[[7]],c(maritalStat="Marital Status")),P=varlvlsum$`Pr(>Chisq)`[7]),
             varPlot(rename(isoList[[8]],c(media="Media")),P=varlvlsum$`Pr(>Chisq)`[8]),
             varPlot(rename(isoList[[9]],c(knowledge="Knowledge")),P=varlvlsum$`Pr(>Chisq)`[9]),
             varPlot(isoList[[10]],P=varlvlsum$`Pr(>Chisq)`[10]),
             nrow=4)

print(varlvlsum)

```

# Partner Year Recency

```{r partner year recency, echo=FALSE,message=FALSE,warning=FALSE}
load(".parterYearRecency_varlvlsum.RData")
source("ordfuns.R")
source("plotFuns.R")
catNames <- c("religion","urRural","job","maritalStat","MCCategory")
predNames <- predfun("recency")
source("iso.R",echo=FALSE,verbose = FALSE)
isoList[[10]]$MCCategory <- factor(isoList[[10]]$MCCategory,levels=c("No","Old","New"))
grid.arrange(varPlot(rename(isoList[[1]],c(age="Age")),P=varlvlsum$`Pr(>Chisq)`[1]),
             varPlot(rename(isoList[[2]],c(wealth="Wealth")),P=varlvlsum$`Pr(>Chisq)`[2]),
             varPlot(rename(isoList[[3]],c(religion="Religion")),P=varlvlsum$`Pr(>Chisq)`[3]),
             varPlot(rename(isoList[[4]],c(edu="Education")),P=varlvlsum$`Pr(>Chisq)`[4]),
             varPlot(rename(isoList[[5]],c(urRural="Area")),P=varlvlsum$`Pr(>Chisq)`[5]),
             varPlot(rename(isoList[[6]],c(job="Job")),P=varlvlsum$`Pr(>Chisq)`[6]),
             varPlot(rename(isoList[[7]],c(maritalStat="Marital Status")),P=varlvlsum$`Pr(>Chisq)`[7]),
             varPlot(rename(isoList[[8]],c(media="Media")),P=varlvlsum$`Pr(>Chisq)`[8]),
             varPlot(rename(isoList[[9]],c(knowledge="Knowledge")),P=varlvlsum$`Pr(>Chisq)`[9]),
             varPlot(isoList[[10]],P=varlvlsum$`Pr(>Chisq)`[10]),
             nrow=4)

print(varlvlsum)

```


# Partner Life Recency

```{r partner life recency, echo=FALSE,message=FALSE,warning=FALSE}
load(".partnerLifeRecency_varlvlsum.RData")
source("ordfuns.R")
source("plotFuns.R")
catNames <- c("religion","urRural","job","maritalStat","MCCategory")
predNames <- predfun("recency")
source("iso.R",echo=FALSE,verbose = FALSE)
isoList[[10]]$MCCategory <- factor(isoList[[10]]$MCCategory,levels=c("No","Old","New"))
grid.arrange(varPlot(rename(isoList[[1]],c(age="Age")),P=varlvlsum$`Pr(>Chisq)`[1]),
             varPlot(rename(isoList[[2]],c(wealth="Wealth")),P=varlvlsum$`Pr(>Chisq)`[2]),
             varPlot(rename(isoList[[3]],c(religion="Religion")),P=varlvlsum$`Pr(>Chisq)`[3]),
             varPlot(rename(isoList[[4]],c(edu="Education")),P=varlvlsum$`Pr(>Chisq)`[4]),
             varPlot(rename(isoList[[5]],c(urRural="Area")),P=varlvlsum$`Pr(>Chisq)`[5]),
             varPlot(rename(isoList[[6]],c(job="Job")),P=varlvlsum$`Pr(>Chisq)`[6]),
             varPlot(rename(isoList[[7]],c(maritalStat="Marital Status")),P=varlvlsum$`Pr(>Chisq)`[7]),
             varPlot(rename(isoList[[8]],c(media="Media")),P=varlvlsum$`Pr(>Chisq)`[8]),
             varPlot(rename(isoList[[9]],c(knowledge="Knowledge")),P=varlvlsum$`Pr(>Chisq)`[9]),
             varPlot(isoList[[10]],P=varlvlsum$`Pr(>Chisq)`[10]),
             nrow=4)

print(varlvlsum)

```


